"""Shared, evidence-eligibility thresholds for performance analysis."""

PERFORMANCE_MIN_CONCURRENT_USERS = 100
PERFORMANCE_MIN_DURATION_SECONDS = 60
PERFORMANCE_MIN_SAMPLE_COUNT = 20
PERFORMANCE_P95_LATENCY_THRESHOLD_MS = 500.0
PERFORMANCE_ERROR_RATE_THRESHOLD_PERCENT = 1.0
